### ISSUE TITLE
[Design] Blockquotes not supposed to be in box/Box misses heading

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-accessibility#14]
The box around the blockquote has an empty header element. We don’t use boxes without headers for visual consistency.

Also, here a box is following an h2 immediately, which looks unpleasant due to the lines “colliding”. 

The blockquote is already distinct enough with its indentation and space around it, imho.

**Comment by shawna-slh** [comment]
Agree don't need box around blockquote. It's gone https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/#intro

Do need better proximity of the attribution with the quote.
Would like no space between quote line and attribution line. Let me know best way to do that.

Also probably want attribution a bit quieter. I didn't go searching for the code to see if the quote text itself is smaller, or just appears that way because of italics...

**Comment by yatil** [comment]
It’s the same text size. I tried to use best practices for quotes from a micro typography standpoint. Especially if we have multiple paragraphs in a quote we want the space between the quote content and the attribution.
