### ISSUE TITLE
Links to more info

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-accessibility#5]
The page has lots of links throughout to other resources. We would like for those links ***not to interrupt the flow* or clutter the document**. Some links are optional, and other links are key resources.

<h2>Briefly (Editor suggestions)</h2>

One option is to put the more info at the end of each section, and collapsed, as in this version:
**[Alternative 5](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt5)**

Another option is to put all the links and the end of the resources, as in this version:
**[Alternative 7](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt7)**

<h2>Details and More Alternatives</h2>

**[Previous Version](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/2018-Jan-10-version)**

The 10-12 Jan version had some links in boxes floated right, and some inline. Here are some pros, cons, considerations:
* float-right is hard (impossible?) to get in right source order and visual placement
* float-right would go in-line for mobile devices, big zoom, etc.
* float-right might be missed by screen magnification users
* float-right works really well in the "What is Web Accessibility" section where they are next to lists *and* the links are optional. _(possibly we do inline for others, and float-right just for those?)_
* in-line interrupts flow more, and makes it longer scrolling

**[Alternative 3](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt3) and [Alternative 5](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt5)**

This version has more links at the end of each section, collapsed.
* Alt 3 has them has headings
* Alt 5 has them a paragraphs

Pro: Gets rid of the clutter/flow-block of the more info links out of the default view of the page.
Con: The Expand button and "More info links" themselves still are some clutter/flow-block

**[Alternative 6](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt6) and [Alternative 7](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt7)**

These versions put all the links at the very end of the page.
* Alt 6 has them always visible
* Alt 7 has them collapsed by default

Pro: Totally gets rid of the clutter and flow blob of having them throughout the doc
Con: As people read through the document, if they want more info on a specific topics, it's harder to find it at the bottom.

**[Alternative 4](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt4) and [Alternative 2](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt2)**

These versions have the more info links at the end of each section. They are still in boxes.
* Alt 4 has them left aligned
* Alt 2 has them indented a bit

**Your thoughts on these or other approaches?**

**Comment by yatil** [comment]
[All Editor’s discretion.] Seeing this, I really like the “Alternative 7” version because it makes the whole document smaller and easier to digest. Some additional thoughts:

* If we would go with 7, I think we can get rid of the table of contents and just dive right in. Having a table of contents makes the document feel longer and more complicated than it really is, imho.
* While I like to have the “for more info” content, I wonder if that is really necessary with the new design and a better overview that comes with it. Especially if we have the audience navigation, we might be OK listing those at some time. Really happy to leave as is for now.

**Comment by lakeen** [comment]
I prefer Alternative 5.  I like the "more info" link being in place where context is easy to follow.  I do think the + expand/collapse buttons background color could be muted a bit.

**Comment by bakkenb** [comment]
100% agree with @lakeen on this one. I don't like Alt 7 because as I was pretending to read through as a first time viewer, I got to the bottom and then realized each section had more links, but the links are not in context with the important content. 

When I look at Alt 5, my minds says, "there are more links here to look at. I am interested in this specific topic so I want to look at these links too." ~or~ "... there are more links here about this topic, but I want to keep reading to see what else is on the page. I will come back if needed." It was better to me to know there were more links available if I was interested **_while_** I was reading, not after.

I also agree to mute the "+" (expand) icons, they are too dark and pull attention to much.

If people absolutley do not like the expand/collapse for More Info Links, then I would be happy implementing Alt 2 (indented), but the pages will be longer.

**Comment by yatil** [comment]
(I have spun the discussion around the visuals for expand collapse off to a separate thread at w3c/wai-website-design#104.)

**Comment by iamjolly** [comment]
[Editor's discretion] I really like Alt 2 - showing the links up front but with the indented, box design really helps make it clear. A longer page here is OK to me since the design doesn't require me to read every word/paragraph to get what I need.

**Comment by vavroom** [comment]
[Editor's discretion] My preference would be for alt 7, though I'm happy with alt 5 as well.

I second @yatil suggestion of getting rid of the TOC

**Comment by nrhsinclair** [comment]
I prefer alt 7. I personally do not like to expand and collapse multiple items on a page. I am ok with all the "more info links" at the bottom of the page. I am also going to suggest that "Examples of web accessibility" is not needed at all on this page. I would rather highlight the perspective videos to the user just learning about web accessibility. I think that link needs additional emphasis, it can easily be overlooked. Perhaps move the link to video to the beginning of the paragraph, rather than the end: Check out: Web Accessibility Perspectives Video to see a 7-minute video with examples of ...

I really like the revised content of this page. Although there is much content, it is very readable.

**Comment by a11ycob** [comment]
I like ALTs 2 or 4. They appear very clean to my eye, and the color differentiation of the "more info" sections really breaks up the page well. Semantically, I think think the use of headers and aside landmarks work well together.
In general, can live without the expand and collapse functionality.

**Comment by hkramer** [comment]
I like alt 2. The slight indent helps distinguish those items from the rest of the doc.

**Comment by shawna-slh** [comment]
Helpful to get different perspectives!

Some replies:
* The redesign template has the Page Contents as the first thing on all pages -- based on usability testing feedback. The draft revision is being modified to match.
* We'll work on a quieter expand/collapse button (whether or not we use it on this page). (https://github.com/w3c/wai-website-design/issues/104)
* "not like to expand and collapse multiple items on a page" We would probably have an "expand all" button if we go with this. Maybe most readers won't expand most of the items in one read – and only expand those that they are interested in, when they're ready for them?
**See [Brent's walkthrough above](https://github.com/w3c/wai-intro-accessibility/issues/5#issuecomment-358126950)**

(other points will be covered in separate GitHub issues, flagged for the commenter)

**Comment by shawna-slh** [comment]
Reminder that a primary goal of this revision is to make the content easy to skim, easy to read, less dense, and hopefully shorter.

Based on all input above, I propose narrowing it down to **two options:**

**[Alternative 2](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/links-alt2)**
_More info links in boxes that are indented a bit._
**Pro:** Users can see the More Info links without having to expand sections.
**Con:** Makes the page much longer and visually more complex.

**[Alternative 5](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/)**
_More info links collapsed._
**Pro:** Page is much shorter with More Info links collapsed.
**Con:** Users have to click to see what's in the More Info.
**Note:** We're planning to make the [expand button quieter](https://github.com/w3c/wai-website-design/issues/104).
p.s. I don't think we've done any usability testing specifically on the expand-collapse.

<hr/>

_**Put yourself in readers shoes, different people with different styles...**_ <------------------

**Other pros and cons you can think of?**

**Please comment on which pros and cons you think are stronger considerations based on our goals, the target audience, etc. – and thus which option bubbles to the top.**

**Comment by yatil** [comment]
* I don’t feel that this would be a particularly good use case for an expand/collapse as the info is scattered around the page. (see w3c/wai-website-design#106)

* I still find a collection of additional links on the bottom more clear. Unsure about the organization of such links, that looked a bit clunky.

* That said, I think any variant is fine in general. I slightly prefer having expand/collapse. (Alternative 5) Editor’s discretion.

**Comment by yatil** [comment]
> The redesign template has the Page Contents as the first thing on all pages -- based on usability testing feedback. The draft revision is being modified to match.

Did we agree to put it on ALL pages? Even if they have only a few sections? Should inform our decisions in w3c/wai-website-design#108.

**Comment by nrhsinclair** [comment]
Looking at the variations again, 7 is the one I more slowly work through, stopping to read more. I find myself automatically skimming and scrolling more quickly with most of the other variations. I like the idea, that when returning to the page a second and third time, the additional resource that I remember was linked somewhere on the page, would be easier to find listed at the bottom of the page. The table of contents on the page works well for me, provides context and lets me know there is a good bit of information on the page below.

**Comment by bakkenb** [comment]
Between Alt 2 and Alt 5, I prefer Alt 2. 
I am going to open the expand/collapse anyway (that is my nature), might as well just have it showing and indented. Much more simple.

**Comment by yatil** [comment]
I find the indentation generally introduces a tiny bit more clutter.

**Comment by a11ycob** [comment]
Out of the two options #2 is the one I would select

**Comment by shawna-slh** [comment]
ACTION: More info on [topic]

**Comment by shawna-slh** [comment]
Resolution from [18 Jan telecon](https://www.w3.org/2018/01/18-eo-minutes.html#item05):

Essentially Alternative 4:
* More info in boxes (no expand-collapse)
* Left aligned (not indented)
* More info on [heading (may shorten somewhat)]
* More white space above h2

Resolution will be listed in EOWG survey for all to review. Can also re-open this issue if concerns...
