### ISSUE TITLE
[ED] Summary at top

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-accessibility#6]
> Properly designed and coded websites and tools can be used by people with disabilities. However, currently many sites and tools are developed with accessibility barriers that make it difficult or impossible for some people to use them. This page explains more about:
* Accessibility in Context
* What is Web Accessibility
* Accessibility is Important for Individuals, Businesses, Society
* Making the Web Accessible
* Evaluating Accessibility
* Examples of Web Accessibility
...

The text at the top of the 10-12 Jan draft isn't quite a summary -- it's more like the important baseline for the document. Is this OK? Other ideas?

**Comment by shawna-slh** [comment]
@VivienneConway commented in the 12 Jan teleconference about maybe adding something about additional benefits in the summary.

So far I didn't come up with a smooth, succinct idea for that. I did tweak the heading that is listed:

> Accessibility is Important for Individuals, Businesses, Society

More input welcome!

**Comment by bakkenb** [comment]
Thanks for the good question. At first I did not notice that this was not a true summary. When you ask the question "is this okay," I thought that it was fine. But the more I think about it, the more I disagree. 

I think we had some good discussion on several occasions about adding "summary" boxes to the tops of a lot of our resources/pages so that visitors could quickly get the main points of the page and move on if they wanted, or dive deeper and read the entire page. 

If that is in fact the direction we are going, then this summary box needs to serve the same purpose to be consistent across the site. We have to be careful how we do these summary boxes. There is a fine line between giving a simple, brief summary, vs. giving a detailed summary followed by a page that says the same thing. Should the summary just be "what is on this page" type information? If so, maybe all you need to do is add a second small paragraph detailing out the bulleted list a little.

**Comment by sharronrush** [comment]
What about leaving as is and just calling it an "Introduction" rather than a "Summary"

**Comment by shawna-slh** [comment]
Related comment: https://github.com/w3c/wai-intro-accessibility/issues/3#issuecomment-358448196

**Comment by shawna-slh** [comment]
Went with @sharronrush 's idea to leave as is and call Introduction.

Feel free to re-open if needed.

**Comment by shawna-slh** [comment]
There is some support for this text, including from [Sarah ](https://www.w3.org/2018/02/01-eo-minutes.html#item04)& [Norah](https://github.com/w3c/wai-intro-accessibility/issues/3#issuecomment-358448196), and some question about its placement as an Introduction from [Shadi](https://www.w3.org/2002/09/wbs/35532/Intro-Review-2018-Jan/results). I agree with all three -- that it's good to have those sentences up front, but they were not smooth as they were.

I'm trying an option with an updated Summary that actually is a summary of the page content. It's in place here: https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/alt-summary

The last two sentence are new:

> ## Summary
> When websites and web tools are properly designed and coded, people with disabilities can use them. However, currently many sites and tools are developed with accessibility barriers that make them difficult or impossible for some people to use.
>
> Making the web accessible benefits individuals, businesses, and society. International web standards define what is needed for accessibility.

**Comment by shawna-slh** [comment]
OKed by EO-Plan.

Listed for EOWG review in https://www.w3.org/WAI/EO/wiki/Accessibility_Intros_Notes#Changes_since_30_January
